secrets:
  proxy.certificate:
    file: ./keys/fullchain.pem
  proxy.key:
    file: ./keys/privkey.pem

services:
  proxy:
    image: nginx:alpine
    ports:
      - target: 443
        published: 443
      - target: 2053
        published: 2053
      - target: 2083
        published: 2083
    deploy:
      mode: replicated
      replicas: 1
    environment:
      KIBANA_PORT: ${KIBANA_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    networks:
      - elastic

networks:
  elastic:
    external: true
